alpaca_api_key: "PKJN9S6SYMCYI59NCR51"
alpaca_secret_key: "jTEcQCY9tNP1MdvQRMggu34TaH504MttI36BwOcu"
alpaca_base_url: "https://paper-api.alpaca.markets"

pg_host:     "localhost"
pg_port:     5432
pg_name:     "tradejournal"
pg_user:     "tommy"
pg_password: "opal-eskimo-newark"

finnhub_api_key: "d1b9s0hr01qjhvtt9dpgd1b9s0hr01qjhvtt9dq0"